spring.application.name=Job_Matching_and_Recruitment_System

# Config datasource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/Job_Matching_and_Recruitment_System?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Config jpa
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Config jwt
jwt-secret=${JWT_SECRET}
jwt-expired=600000 
jwt-refresh-expired=15552000000
jwt-reset-secret=${JWT_RESET_SECRET}

# Config Cloudinary
cloudinary.cloud-name=dll6mpwhk
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# Config Multipart Upload
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}